import{a as f,S as g,i}from"./assets/vendor-D1eTGYtO.js";(function(){const a=document.createElement("link").relList;if(a&&a.supports&&a.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))o(t);new MutationObserver(t=>{for(const r of t)if(r.type==="childList")for(const l of r.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&o(l)}).observe(document,{childList:!0,subtree:!0});function s(t){const r={};return t.integrity&&(r.integrity=t.integrity),t.referrerPolicy&&(r.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?r.credentials="include":t.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function o(t){if(t.ep)return;t.ep=!0;const r=s(t);fetch(t.href,r)}})();const y="https://pixabay.com/api/",v="38315380-10eeb0cf3b6e9a9ad49e9c507";async function L(e,a=1){try{return(await f.get(y,{params:{key:v,q:e,image_type:"photo",orientation:"horizontal",safesearch:!0,page:a,per_page:15}})).data}catch(o){throw console.error("Error fetching data from Pixabay API",o),o}}const p=document.querySelector(".gallery-list");let d;function b(e){const a=e.map(s=>`<li class="image-wrapper">
    <a href="${s.largeImageURL}">
    <img class="gallery-img" src="${s.webformatURL}" alt="${s.tags}"></img>
    </a>
    <div class="text-wrapper">
    <div class="text-item"><h5 class="text-header">Likes</h5><p class="text-paragraph">${s.likes}</p></div>
    <div class="text-item"><h5 class="text-header">Views</h5><p class="text-paragraph">${s.views}</p></div>
    <div class="text-item"><h5 class="text-header">Comments</h5><p class="text-paragraph">${s.comments}</p></div>
    <div class="text-item"><h5 class="text-header">Downloads</h5><p class="text-paragraph">${s.downloads}</p></div>
    </div>
    </li>`).join("");p.insertAdjacentHTML("beforeend",a),d?d.refresh():d=new g(".gallery-list a",{captions:!0,captionsData:"alt",captionsDelay:250})}function w(){p.innerHTML=""}const x=document.querySelector(".form"),P=document.querySelector(".form-input"),u=document.querySelector(".loader"),n=document.querySelector(".load-btn");let c=1,h="";x.addEventListener("submit",S);n.addEventListener("click",q);async function S(e){if(e.preventDefault(),w(),c=1,h=P.value.trim(),!h){i.warning({position:"bottomRight",message:"Please enter a search term"});return}await m()}async function q(){c+=1,await m(),R()}async function m(){u.classList.remove("hidden"),n.classList.add("hidden");try{const e=await L(h,c);e.totalHits===0?i.warning({position:"bottomRight",message:"Sorry, there are no images matching your search query. Please try again!"}):(b(e.hits),e.hits.length<15||c*15>=e.totalHits?(n.classList.add("hidden"),i.info({position:"bottomRight",message:"We're sorry, but you've reached the end of search results."})):n.classList.remove("hidden"))}catch(e){i.error({position:"bottomRight",message:"Failed to fetch images."}),console.error(e)}finally{u.classList.add("hidden")}}function R(){const{height:e}=document.querySelector(".gallery-list").firstElementChild.getBoundingClientRect();window.scrollBy({top:e*2,behavior:"smooth"})}
//# sourceMappingURL=commonHelpers.js.map
